services:
  mongodb:
    image: "mongo:latest"
    networks:
      - mongo_network
    restart: always
    environment:
      - "MONGO_INITDB_DATABASE=HouseholdAccountBookDB"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
      - "MONGO_INITDB_ROOT_USERNAME=root"
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: "mongo-express:latest"
    networks:
      - mongo_network
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongodb

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local